### ISSUE TITLE
Code of Conduct attribution cleanup

### ISSUE THREAD

**Issue by emmet0r** [emmet0r/osre-catalyst#9]
Our CoC could use a more robust "attribution" section. It contains pointers to our source material; these are good starting points to how we can give proper credit.

**Comment by OnexiMedina** [comment]
@thatguyseven and me are working on it! Will send the changes soon when we are done reviewing the CoC.

**Comment by emmet0r** [comment]
Closed with #10 . Thanks @OnexiMedina & @thatguyseven !
